# Generated by Django 3.2.12 on 2022-03-27 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Predication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
                ('gender', models.PositiveIntegerField(choices=[(1, 'Male'), (0, 'Female')])),
                ('resting_bp_s', models.PositiveIntegerField()),
                ('cholestrol', models.PositiveIntegerField()),
                ('fasting_blood_sugar', models.PositiveIntegerField()),
                ('old_peak', models.PositiveIntegerField()),
                ('chest_pain_type', models.PositiveIntegerField(choices=[(1, 'Typical'), (2, 'Typical Angina'), (3, 'Non Anginal Pain'), (4, 'Asymptomatic')])),
                ('target', models.PositiveIntegerField(choices=[(0, 'Normal'), (1, 'Patient is suffering from heart risk')])),
                ('st_slope', models.PositiveIntegerField(choices=[(0, 'Normal'), (1, 'Up Sloping'), (2, 'Flat'), (3, 'Down Sloping')])),
                ('exercise_angina', models.PositiveIntegerField(choices=[(0, 'Depicting No'), (1, 'Depicting Yes')])),
                ('resting_ecg', models.PositiveIntegerField(choices=[(0, 'Normal'), (1, 'Abnormality in ST-T Wave'), (2, 'Left Ventricular Hypertrophy')])),
                ('max_heart_rate', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
