# Generated by Django 3.2.12 on 2022-03-27 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220328_0004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predication',
            old_name='avg_vocal_fundamental_frequency',
            new_name='mdvp_jitter',
        ),
        migrations.RenameField(
            model_name='predication',
            old_name='jitter',
            new_name='mdvp_shimmer',
        ),
        migrations.RemoveField(
            model_name='predication',
            name='max_vocal_fundamental_frequency',
        ),
        migrations.RemoveField(
            model_name='predication',
            name='min_vocal_fundamental_frequency',
        ),
        migrations.RemoveField(
            model_name='predication',
            name='pitch',
        ),
        migrations.RemoveField(
            model_name='predication',
            name='shimmer',
        ),
        migrations.AddField(
            model_name='predication',
            name='mdvp_fhi',
            field=models.IntegerField(default=0, help_text='Minimum Vocal Fundamental Frequency'),
        ),
        migrations.AddField(
            model_name='predication',
            name='mdvp_flo',
            field=models.IntegerField(default=0, help_text='Maximum Vocal Fundamental Frequency'),
        ),
        migrations.AddField(
            model_name='predication',
            name='mdvp_fo',
            field=models.IntegerField(default=0, help_text='Average Vocal Fundamental Frequency'),
        ),
    ]
